// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQ8-ohgmfGyGADxXSZvQ1MbiWQn-Gotc',
    appId: '1:509440259188:web:92618b01dfa88a9a724d21',
    messagingSenderId: '509440259188',
    projectId: 'chatly-messaging-app-8391c',
    authDomain: 'chatly-messaging-app-8391c.firebaseapp.com',
    storageBucket: 'chatly-messaging-app-8391c.firebasestorage.app',
    measurementId: 'G-EXY47FH3W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEODrcwYvicbXrTrlcdjdQK0oqCCp4qPE',
    appId: '1:509440259188:android:db148ec8855144a8724d21',
    messagingSenderId: '509440259188',
    projectId: 'chatly-messaging-app-8391c',
    storageBucket: 'chatly-messaging-app-8391c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCStdPC72CAPp3_32nb_PCgLep1ZroTblk',
    appId: '1:509440259188:ios:0ffb60314da73866724d21',
    messagingSenderId: '509440259188',
    projectId: 'chatly-messaging-app-8391c',
    storageBucket: 'chatly-messaging-app-8391c.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );
}
