// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfAqJVuThPhMJaSds8VidhIjJ129vwLGM',
    appId: '1:585617938137:web:7e488cff40d599995ad0c8',
    messagingSenderId: '585617938137',
    projectId: 'chatly-messaging-app-6266a',
    authDomain: 'chatly-messaging-app-6266a.firebaseapp.com',
    storageBucket: 'chatly-messaging-app-6266a.firebasestorage.app',
    measurementId: 'G-VNXL2H5C4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB73zhGm7iCvA1rML-d8ABeBWo7I9c3A9g',
    appId: '1:585617938137:android:879a8e97a16d006b5ad0c8',
    messagingSenderId: '585617938137',
    projectId: 'chatly-messaging-app-6266a',
    storageBucket: 'chatly-messaging-app-6266a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFfV05xLKAnbr_4jRcov1SMK8iK2qWQTg',
    appId: '1:585617938137:ios:74cce846279b5be25ad0c8',
    messagingSenderId: '585617938137',
    projectId: 'chatly-messaging-app-6266a',
    storageBucket: 'chatly-messaging-app-6266a.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );
}
